In [1]:
import torch
from requests.packages import target

In [2]:
mylist = [[1,2,3],[4,5,6]]
tensor = torch.tensor(mylist)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
#  cong tru tensor giong nhu cong tru trong numpy va dai so tuyen tinh, chung phai tuong thich, nghia la co cung` kich thuoc

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


In [5]:
# xay dung mang noron co ban
import torch.nn as nn

# tao dau vao tenser voi 3 features dac trung
input_tensor = torch.tensor([[0.3471,0.4547,-0.2356]])

# dinh nghia layout linearn
linear_layer = nn.Linear(
    in_features=3,
    out_features=2
)
output = linear_layer(input_tensor)
print(output)

# đầu vào + trọng số w + độ lệch b =  đầu ra
# lúc đầu các chỉ số được gán ngẫu nhiên, do đó mà ta phải tinh chỉnh lại


# trong số weight w, phản ảnh mức độ quan trọng của từng đặc trưng
# print(linear_layer.weight)

# độ lệch .bias b cung cấp đầu ra cơ sở cho nơ ron
# print(linear_layer.bias)

tensor([[ 0.7042, -0.4085]], grad_fn=<AddmmBackward0>)


In [6]:
"""
Xếp tầng với nn.Sequetial()
model = nn.Sequetial(
nn.Linear(n_features, 8),
nn.Linear(8,4),
nn.Linear(4, n_classes))

việc này sẽ làm nó truyền qua từng tầng tuyến tính rồi mới ra bằng đầu ra 
các tầng bên trong sequetial là các tầng ẩn
như kia là có 3 tầng:
    đối số đầu tiên của tầng thứ nhất là đặc trưng đầu vào(n_features)
    đối số cuối cùng của tầng cuối là số lớp đầu ra (n_classes)
    cả 2 đều do bộ dữ liệu xác định

Ví dụ
model = nn.Sequetial(
nn.Linear(10,18),
nn.linear(18,20),
nn.Linear(20,5)
)
trong ví dụ này thì có 3 tầng, tầng 1 nhận 10 xuất ra 18, tầng 2 nhận 18 xuất ra 20, tầng 3 nhận 20 và xuất ra 5
Một tầng được gọi là kết nối dầy đủ khi mỗi nơ ron liên kết với tất cả nơ ron ở tầng trước nó

Một nơ-ron ở tầng tuyến tính:
    - thực hiện phép tuyến tính dùng mọi rơ-ron ở tầng trước
    - như vậy 1 rơ ron đơn lẻ có n+1 tham số, có thể học từ n đầu vào và 1 bias riêng lẻ

"""

# tham số và năng lực mô hình
# Nhiều tầng ẩn hơn -> mô hình nhiều tham số hơn -> năng lực mô hình sẽ cao và chuẩn xác hơn, có thể xử lý bộ dữ liệu phức tạp hơn nhưng sẽ mất nhiều thời gian huấn luyện hơn
# 1 cách đánh giá được mô hình là tính tổng số tham số của nó
# vd
model = nn.Sequential(nn.Linear(8,4),nn.Linear(4,2))

#  tầng thứ nhất có 4 nơ ron, mỗi nơ ron có 8 tham số -> (8+1)x4 = 36 tham số
# tầng thứ 2 có 2 nơ ron, mỗi nơ ron có 4 tham số -> (4+1)x2 = 10 tham số
# tổng mô hình có 46 tham số có thể học
# trong tensor có 1 phương thức có thể tính được tổng só tham số đó là . numel()

total = 0
for parameter in model.parameters():
    total += parameter.numel()
print(total)

46


In [7]:
# hàm kích hoạt: hàm kích hoạt thêm phi tuyến tính cho mạng
# - Đau vao -> cac lop tuyen tinh -> kich hoat -> dau ra
# co 2 ham kich hoat co ban
# sigmoid: cho phan loai nhi phan (0,1)
# softmax: cho phan loai da lop
# tinh phi tuyen nay cho phep mang hoc duoc cac quan he phuc tap hon
# sigmoid == nn.Sigmoid()




NameError: name 'sigmoid' is not defined

In [ ]:
"""
truyen xuoi la du lieu dau vao di qua cac tang, tinh toan o moi tang, tang cuoi cung tao ra dau ra

dau ra dua vao trong so va do lech, quan trong ca huan luyen va du doan

dau ra co the la:
    phan loai nhi phan
    phan loai da lop
    hoi quy

"""
# input_data = tensor.tensor([[],[],[],[],[]])



"""
phan loai da lop truyen xuoi
1, dong vat co vu
2, chim
3, bo sat
"""
n_classes = 3
model = nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,n_classes),
    nn.Softmax(dim=-1)
)
output = model(input_tensor)


"""
Hoi quy :truyen xuoi
"""



In [11]:
"""
Ham mat mat: ham nay nhan y ground truth lam dau vao,
"""

# encoding
import torch.nn.functional as F
print(F.one_hot(torch.tensor(0), num_classes = 3))
#tuong tu ung voi tung vi tri, hien tai dang la vi tri y =0

#voi vi tri y bang 1
print(F.one_hot(torch.tensor(1), num_classes = 3))

# tuong tu voi vi tri y = 2
print(F.one_hot(torch.tensor(2),num_classes  = 3))

tensor([1, 0, 0])
tensor([0, 1, 0])
tensor([0, 0, 1])


In [13]:
# ham mat mat cross entroty trong pytorch
from torch.nn import CrossEntropyLoss

score = torch.tensor([-5.2,4.6,0.8])
one_hot_target = torch.tensor([1,0,0])

criterion = CrossEntropyLoss()

print(criterion(score.double(), one_hot_target.double()))

tensor(9.8222, dtype=torch.float64)


In [ ]:
# lan truyen nguoc trong pytorch


model = nn.Sequential(
    nn.Linear(16,8),
    nn.Linear(8,4),
    nn.Linear(4,2)
)
prediction = model(sample)
#calculate the loss function and gradient
criterion  = CrossEntropyLoss()
loss= criterion(prediction, target)
loss.backward()

# model[0].weight.grad
# model[0].bias.grad
# model[1].weight.grad
# model[1].bias.grad

In [ ]:
# tu cap nhat tham so mo hinh
lr = 0.001

#update the weight
weight = model[0].weight
weight_grad = model[0].weight.grad
# su dung cong thuc lien quan toi leaning rate
weight = weight - lr * weight_grad

# update the bias
bias = model[0].bias
bias_grad = model[0].bias.grad

bias = bias - lr * bias_grad

In [ ]:
# gradient descent
import torch.optim as optim

#create the optimizer
optimizer = optim.SGD(model.parameters(),lr = 0.01)

#perform parameter step
optimizer.step()

In [ ]:
import torch
from torch.utils.data import TensorDataset

# khoi tao dataset
dataset = TensorDataset(torch.tensor(X), torch.tensor(y))

# truy cap 1 mau don le
input_sample,label_sample = dataset[0]
print("input sample:", input_sample)
print("label sample:", label_sample)


In [ ]:
#dataloader
from torch.utils.data import DataLoader

batch_size = 2
shuffle= True

# taoj loader dataset
dataloader = Dataloader(dataset, batch_size = batch_size, shuffle= shuffle)


#epoch: 1 luot duyet day du qua dataset huan luyen
#kha nang khai quat hoa: mo hinhf hoat dong tot tren du lieu chua tung xuat hien

# lap qua dataloader
for batch_inputs,batch_labels in dataloader:
    print(batch_inputs)

In [ ]:
# tinh mse: trung binh chenh lech giua du doan va nhan goc
def mse(predict, target):
    return np.mean((predict - target)**2)

# trong pytorch
criterion  = nn.MSELoss()
loss = criterion(prediction, target)

In [ ]:
# truoc vong lap

#khoi tao dataset
dataset = TensorDataset(torch.tensor(features),
                        torch.tensor(target))
# load dataset
dataloader = DataLoader(dataset, batch_size=4 , shuffle=True)

# khoi tao model
model = nn.Sequential(nn.Linear(8,4),nn.Linear(4,2))

# khoi tao ham loss
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(),lr = 0.01)



# trong vong lap
