In [2]:
# addition of arrays
import numpy as np
a= np.array([2,3,4,5])
b = np.array([2,3,4,5])
res = np.add(a,b)
print(list(res))
print(res)

[np.int64(4), np.int64(6), np.int64(8), np.int64(10)]
[ 4  6  8 10]


In [4]:

#subtract
res1 = np.subtract(a,b)
print(res1)


[0 0 0 0]


In [5]:
#multiply
res2 = np.multiply(a,b)
print(res2)

[ 4  9 16 25]


In [9]:
#divide
res3 = np.divide(a,b)
print(res3)
print(list(res3))

[1. 1. 1. 1.]
[np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0)]


In [ ]:
import numpy as np

arr = np.array([ [14, 17, 12, 33, 44],
               [15,  6, 27,  8, 19],
               [23,  2, 54,  1,  4] ])

print(np.sum(arr))
print(np.sum(arr, dtype=np.uint8)) # chi bieu dien 2^8 tức là từ 0 tới 255 được thôi, từ 256 thì lấy res - 255 = 
print(np.sum(arr, dtype=np.float32))

279
23
279.0


In [14]:
import numpy as np

arr = np.array([ [14, 17, 12, 33, 44],
               [15,  6, 27,  8, 19],
               [23,  2, 54,  1,  4] ])

print(arr.sum(axis = 0)) #52
print(np.sum(arr,axis= 0))

print(arr.sum(axis = 1)) #

[52 25 93 42 67]
[52 25 93 42 67]
[120  75  84]
