In [1]:
import sys
print(sys.executable)
%pip install numpy

c:\Su\su\.venv\Scripts\python.exe
Note: you may need to restart the kernel to use updated packages.


c:\Su\su\.venv\Scripts\python.exe: No module named pip


In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


c:\Su\su\.venv\Scripts\python.exe: No module named pip


In [1]:
# create numpy array

import numpy as np
a1 = np.array([1,2,3])  # 1D array
a2 = np.array([[1,2],[3,4]]) #2D array
a3 = np.array([[[1,2],[3,4]],
              [[4,5],[5,6]]]) #3d

print(a1)
print(a2)
print(a3)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[4 5]
  [5 6]]]


In [13]:
import numpy as np
arr = np.linspace(2.5, 20, 5, dtype=np.int32)
print(arr)

[ 2  6 11 15 20]


In [86]:
import numpy as np
arr = np.empty((4, 3), dtype=np.int32)
print(arr)

[[4128860 6029375 3801155]
 [5570652 6619251 7536754]
 [4980828 7209061 7733359]
 [6029423 7340097 4456560]]


In [87]:
import numpy as np

ar = np.random.rand(2, 3)
an = np.random.randn(2, 2)
ai = np.random.randint(1, 10, size=(2, 3))  

print(ar)
print(an)
print(ai)

[[0.13724114 0.61231977 0.81564727]
 [0.31188127 0.41293408 0.20587634]]
[[ 0.24178835 -1.85282409]
 [ 0.2785445   2.70905898]]
[[9 1 7]
 [4 9 6]]


In [90]:
import numpy as np

im = np.eye(4)
da = np.diag([1, 2, 3,4])
a0 = np.zeros_like(da)
a1 = np.ones_like(da)

# print(im)
print(da)
# print(a0)
# print(a1)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [92]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]


In [95]:
import numpy as np

arr = np.array([[1],[2],[3]])

print(arr[:, np.newaxis])

[[[1]]

 [[2]]

 [[3]]]


In [ ]:
import numpy as np

arr = np.array([
    [[5, 10, 15], [20, 25, 30], [35, 40, 45]],
    [[2,  4,  6], [ 8, 10, 12], [14, 16, 18]],
    [[7, 14, 21], [28, 35, 42], [49, 56, 63]]
])
print("Array:")
print(arr)

res = arr[:, :2, :2]   # first 2 rows and first 2 columns from each 2D slice
print("Accessed Elements:")
print(res)

In [103]:
import numpy as np

arr = np.array([[101, 20, 3, 10], [40, 5, 66, 7], [70, 88, 9, 141]])
print("Array:")
print(arr)

res = arr[:,1::2]
print("Accessed Row :")
print(res)


Array:
[[101  20   3  10]
 [ 40   5  66   7]
 [ 70  88   9 141]]
Accessed Row :
[[ 20  10]
 [  5   7]
 [ 88 141]]


In [109]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
r = a.reshape(2, 4)
print(r)

[[1 2 3 4]
 [5 6 7 8]]


In [111]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
r = a.reshape(3, -1)
print(r)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [118]:
import numpy as np

x = np.array([1, 2])

y = np.array([7, 8])

print(np.stack((x, y), axis=0))
print(np.stack((x, y), axis=1))
# print(np.stack((x, y), axis=2))
# print((np.stack((x, y), axis=2)).shae)


[[1 2]
 [7 8]]
[[1 7]
 [2 8]]


In [ ]:
import numpy as np
arr = np.arange(13)
# res = np.array_split(arr, 4)
res = np.split(arr, 4)
print(res)

ValueError: array split does not result in an equal division

In [ ]:
import numpy as np

arr = np.arange(24).reshape((2, 3, 4))
# print(arr)

res = np.dsplit(arr, 4)
print(res)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[array([[[ 0],
        [ 4],
        [ 8]],

       [[12],
        [16],
        [20]]]), array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]]), array([[[ 2],
        [ 6],
        [10]],

       [[14],
        [18],
        [22]]]), array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])]


In [125]:
import numpy as np

img = np.array([ [100, 120, 130],
                 [90, 110, 140],
                 [80, 100, 120] ])

m = img.mean(axis=0)
s = img.std(axis=0)
print(m)
print(s)
# res = (img - m) / s
# print(res)

[ 90. 110. 130.]
[8.16496581 8.16496581 8.16496581]


In [126]:
a = np.array([1, 2, 3], dtype=np.float32)
b = np.array([1, 2, 3])
print(a.dtype, b.dtype)
print(a + b)
print((a + b).dtype)

float32 int64
[2. 4. 6.]
float64


In [127]:
a = np.array([[1, 2], [3, 4]])
print(a.itemsize, a.nbytes)


8 32
