In [ ]:
import numpy as np

In [14]:
# b1
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a+b)
print(np.add(a,b))

print(a-b,'\n', np.subtract(a,b))

print(a*b)

print(np.dot(a,b))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]] 
 [[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
# b2
def create_matrix(rows, cols, fill_value):
    a = np.full((rows,cols),fill_value)
    return a
full_7 = create_matrix(3,4,7)
print(full_7)
full_7_T = full_7.T
print(full_7_T)

resh = full_7.reshape(4,3)
print(resh)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
