In [ ]:
import numpy as np

In [14]:
# b1
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a+b)
print(np.add(a,b))

print(a-b,'\n', np.subtract(a,b))

print(a*b)

print(np.dot(a,b))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]] 
 [[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [25]:
# b2
def create_matrix(rows, cols, fill_value):
    a = np.full((rows,cols),fill_value)
    return a
full_7 = create_matrix(3,4,7)
print(full_7)
full_7_T = full_7.T
print(full_7_T)

resh = full_7.reshape(4,3)
print(resh)

fla = full_7.flatten()
print(fla)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
[7 7 7 7 7 7 7 7 7 7 7 7]


In [32]:
#b3
import numpy as np
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)
c  = np.arange(1,9).reshape(4,2)

print(np.dot(np.dot(a,b),c))
print(a@b@c)

[[ 812 1000]
 [1838 2260]]
[[ 812 1000]
 [1838 2260]]


In [ ]:
"""
A1: np.inner(u,v) kết quả là 1 số
np.outer(u,v) kết quả là 1 ma trận kích thước 3x3
inner là tính tích vô hướng còn outer là lấy từng phần tử của A nhân với mảng B

A2: 
là đường chéo của hình bình hành với a và b là 2 cạnh chung gốc
vì nó có z

A3: 
inner thực hiện tích vô hướng trên chiều cuối cùng của axis
[[17,23],
[39,53]]
"""

In [47]:
u = np.array([2,-1,4])
v = np.array([1,5,2])
print((np.inner(v,u)), np.inner(u,v).shape)
print((np.outer(u,v)),np.outer(u,v).shape)
print((np.cross(u,v)),np.cross(u,v).shape)

5 ()
[[ 2 10  4]
 [-1 -5 -2]
 [ 4 20  8]] (3, 3)
[-22   0  11] (3,)


In [ ]:
#b2: tichs vô hướng chia tích độ dài

In [ ]:
"""
topic3
a1: 
deta = 10
a2:
ma trận đơn vị I
a4:

"""